/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface ATACommentDetailsDTO {
  id?: string;
  /** @nullable */
  content?: string | null;
  /** @nullable */
  authorName?: string | null;
  createdAt?: string;
}
