/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ATAStatusDTO } from './aTAStatusDTO';
import type { ATALineItemDetailsDTO } from './aTALineItemDetailsDTO';
import type { ATACommentDetailsDTO } from './aTACommentDetailsDTO';
import type { ATATimelineEntryDTO } from './aTATimelineEntryDTO';

export interface ATADetailsResponseDTO {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  recipientEmail?: string | null;
  /** @nullable */
  requestedBy?: string | null;
  status?: ATAStatusDTO;
  totalCost?: number;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  lineItems?: ATALineItemDetailsDTO[] | null;
  /** @nullable */
  comments?: ATACommentDetailsDTO[] | null;
  /** @nullable */
  timeline?: ATATimelineEntryDTO[] | null;
}
