/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ATAStatusDTO } from './aTAStatusDTO';
import type { ATALineItemForApprovalDtoDTO } from './aTALineItemForApprovalDtoDTO';
import type { ATACommentForApprovalDtoDTO } from './aTACommentForApprovalDtoDTO';
import type { ATATimelineForApprovalDtoDTO } from './aTATimelineForApprovalDtoDTO';

export interface ATAForApprovalResponseDTO {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  requestedBy?: string | null;
  status?: ATAStatusDTO;
  totalCost?: number;
  createdAt?: string;
  /** @nullable */
  lineItems?: ATALineItemForApprovalDtoDTO[] | null;
  /** @nullable */
  comments?: ATACommentForApprovalDtoDTO[] | null;
  /** @nullable */
  timeline?: ATATimelineForApprovalDtoDTO[] | null;
}
