/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ATAStatusDTO } from './aTAStatusDTO';

export interface ATARequestSummaryDTO {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  recipientEmail?: string | null;
  status?: ATAStatusDTO;
  totalCost?: number;
  lineItemCount?: number;
  createdAt?: string;
  updatedAt?: string;
}
