/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export type ATAStatusDTO = typeof ATAStatusDTO[keyof typeof ATAStatusDTO];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ATAStatusDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
