/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export type ATAWorkTypeDTO = typeof ATAWorkTypeDTO[keyof typeof ATAWorkTypeDTO];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ATAWorkTypeDTO = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
