/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface CheckInHabitCommandDTO {
  habitId?: string;
  /** @nullable */
  userId?: string | null;
  isSuccess?: boolean;
  /** @nullable */
  reflection?: string | null;
}
