/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ATAWorkTypeDTO } from './aTAWorkTypeDTO';

export interface CreateATALineItemDtoDTO {
  type?: ATAWorkTypeDTO;
  /** @nullable */
  description?: string | null;
  costEstimate?: number;
  /** @nullable */
  comment?: string | null;
}
