/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface CreateHabitCommandDTO {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  description?: string | null;
}
