/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { CreateATALineItemDtoDTO } from './createATALineItemDtoDTO';

export interface CreateATARequestDtoDTO {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  projectName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  recipientEmail?: string | null;
  /** @nullable */
  requestedBy?: string | null;
  /** @nullable */
  lineItems?: CreateATALineItemDtoDTO[] | null;
}
