/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface CreateUserRequestDTO {
  /** @minLength 1 */
  email: string;
  /** @minLength 6 */
  password: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  firstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  lastName?: string | null;
}
