/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { UserListItemDTO } from './userListItemDTO';

export interface GetAllUsersResponseDTO {
  /** @nullable */
  users?: UserListItemDTO[] | null;
  totalCount?: number;
  page?: number;
  pageSize?: number;
  totalPages?: number;
}
