/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export type GetApiKanbanChatStreamParams = {
conversationId?: string;
message?: string;
boardId?: string;
model?: string;
};
