/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ChatSessionSummaryResponseDtoDTO } from './chatSessionSummaryResponseDtoDTO';

export interface GetBoardChatSessionsResponseDTO {
  boardId?: string;
  /** @nullable */
  currentSessionId?: string | null;
  /** @nullable */
  sessions?: ChatSessionSummaryResponseDtoDTO[] | null;
}
