/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ChatMessageResponseDtoDTO } from './chatMessageResponseDtoDTO';

export interface GetChatSessionMessagesResponseDTO {
  sessionId?: string;
  boardId?: string;
  /** @nullable */
  messages?: ChatMessageResponseDtoDTO[] | null;
}
