/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface KanbanSubtaskDtoDTO {
  /** @nullable */
  title?: string | null;
  isCompleted?: boolean;
  createdAt?: string;
  /** @nullable */
  completedAt?: string | null;
}
