/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { KanbanTaskDtoDTO } from './kanbanTaskDtoDTO';

export interface KanbanColumnDtoDTO {
  id?: string;
  /** @nullable */
  name?: string | null;
  order?: number;
  isCompleted?: boolean;
  /** @nullable */
  tasks?: KanbanTaskDtoDTO[] | null;
}
