/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { KanbanColumnDtoDTO } from './kanbanColumnDtoDTO';

export interface KanbanBoardDtoDTO {
  id?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  createdAt?: string;
  updatedAt?: string;
  /** @nullable */
  columns?: KanbanColumnDtoDTO[] | null;
}
