/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface LoginUserResponseDTO {
  /** @nullable */
  token?: string | null;
  /** @nullable */
  email?: string | null;
  expiresAt?: string;
}
