/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { MessageDTOContent } from './messageDTOContent';
import type { ToolCallDTO } from './toolCallDTO';

export interface MessageDTO {
  /** @nullable */
  role?: string | null;
  /** @nullable */
  content?: MessageDTOContent;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  tool_call_id?: string | null;
  /** @nullable */
  tool_calls?: ToolCallDTO[] | null;
}
