/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface MoveTaskResponseDTO {
  taskId?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  fromColumn?: string | null;
  /** @nullable */
  toColumn?: string | null;
  movedAt?: string;
}
