/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ModelPricingDTO } from './modelPricingDTO';

export interface OpenRouterModelDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  context_length?: number;
  pricing?: ModelPricingDTO;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  features?: string[] | null;
}
