/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface SaveEmailToNewsletterResponseDTO {
  /** @nullable */
  message?: string | null;
  isNewSubscription?: boolean;
}
