/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { ATAStatusDTO } from './aTAStatusDTO';

export interface SubmitATARequestResponseDTO {
  ataId?: string;
  newStatus?: ATAStatusDTO;
  /** @nullable */
  message?: string | null;
}
