/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface ToggleSubtaskResponseDTO {
  taskId?: string;
  /** @nullable */
  taskTitle?: string | null;
  /** @nullable */
  subtaskTitle?: string | null;
  isCompleted?: boolean;
  toggledAt?: string;
}
