/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */
import type { FunctionCallDTO } from './functionCallDTO';

export interface ToolCallDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  type?: string | null;
  function?: FunctionCallDTO;
}
