/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * API
 * Clean Architecture API with JWT Authentication
 * OpenAPI spec version: v1
 */

export interface UpdateUserRequestDTO {
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  firstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  lastName?: string | null;
  /** @nullable */
  email?: string | null;
}
